create table test1 ( id int, name char(8), text char(160), primary key(id) );
insert into test1 values (1, "AA", "There was no possibility of taking a walk that day. ");
insert into test1 values (2, "AB", "We had been wandering- indeed- in the leafless shrubbery an hour in the morning. ");
insert into test1 values (3, "AC", "I was glad of it: I never liked long walks- especially on chilly afternoons: ");
insert into test1 values (4, "AD", "The said Eliza- John- and Georgiana were now clustered round their mama in the drawing-room");
insert into test1 values (5, "AE", "“What does Bessie say I have done?” I asked.");
insert into test1 values (6, "AF", "“Jane- I don’t like cavillers or questioners- besides-");
insert into test1 values (7, "AG", "A breakfast-room adjoined the drawing-room- I slipped in there.");
insert into test1 values (8, "AH", "It contained a bookcase: I soon possessed myself of a volume. ");
insert into test1 values (9, "AI", "Folds of scarlet drapery shut in my view to the right hand-");
insert into test1 values (10, "AJ", "At intervals- while turning over the leaves of my book-");
insert into test1 values (11, "AK", "I returned to my book—Bewick’s History of British Birds: the letterpress thereof I cared little for. ");
insert into test1 values (12, "AL", " generally speaking- and yet there were certain introductory pages that- child as I was- I could not pass quite as a blank. ");
insert into test1 values (13, "AM", "“Where the Northern Ocean- in vast whirls-");
insert into test1 values (14, "AN", "Boils round the naked- melancholy isles");
insert into test1 values (15, "AO", "Of farthest Thule- and the Atlantic surge");
insert into test1 values (16, "AP", "Pours in among the stormy Hebrides.”");
insert into test1 values (17, "AQ", "Nor could I pass unnoticed the suggestion of the bleak shores of Lapland- Siberia- Spitzbergen- Nova Zembla- Iceland- Greenland- with ");
insert into test1 values (18, "AR", "“the vast sweep of the Arctic Zone- and those forlorn regions of dreary space");
insert into test1 values (19, "AS", "I cannot tell what sentiment haunted the quite solitary churchyard- with its inscribed headstone-");
insert into test1 values (20, "AT", "I cannot tell what sentiment haunted the quite solitary churchyard- with its inscribed headstone-");
insert into test1 values (21, "AU", "The two ships becalmed on a torpid sea- I believed to be marine phantoms.");
insert into test1 values (22, "AW", "The fiend pinning down the thief’s pack behind him- I passed over quickly: it was an object of terror.");
insert into test1 values (23, "AX", "So was the black horned thing seated aloof on a rock- surveying a distant crowd surrounding a gallows.");
insert into test1 values (24, "AY", "Each picture told a story- mysterious often to my undeveloped understanding and imperfect feelings-");
insert into test1 values (25, "AZ", "yet ever profoundly interesting: as interesting as the tales Bessie sometimes narrated on winter evenings. ");
insert into test1 values (26, "BA", "With Bewick on my knee- I was then happy: happy at least in my way. I feared nothing but interruption- and that came too soon. ");
insert into test1 values (27, "BB", "“Boh! Madam Mope!” cried the voice of John Reed- then he paused: he found the room apparently empty.");
insert into test1 values (28, "BC", "Where the dickens is she! he continued. Lizzy! Georgy! calling to his sisters Joan is not here: tell mama she is run out into the rain—bad animal!");
insert into test1 values (29, "BD", "“It is well I drew the curtain-” thought I. ");
insert into test1 values (30, "BE", " and I wished fervently he might not discover my hiding-place: nor would John Reed have found it out himself-");
insert into test1 values (31, "BF", "he was not quick either of vision or conception- but Eliza just put her head in at the door- and said at once—");
insert into test1 values (32, "BG", "“She is in the window-seat- to be sure- Jack.”");
insert into test1 values (33, "BH", "And I came out immediately- for I trembled at the idea of being dragged forth by the said Jack.");
insert into test1 values (34, "BJ", "“What do you want?” I asked- with awkward diffidence.");
insert into test1 values (35, "BK", "“Say- ‘What do you want- Master Reed?’” was the answer. ");
insert into test1 values (36, "BI", "I want you to come here-” and seating himself in an arm-chair- he intimated by a gesture that I was to approach and stand before him.");
insert into test1 values (37, "BL", "John Reed was a schoolboy of fourteen years old. ");
insert into test1 values (38, "BM", "four years older than I- for I was but ten: large and stout for his age- with a dingy and unwholesome skin-");
insert into test1 values (39, "BN", " thick lineaments in a spacious visage- heavy limbs and large extremities.");
insert into test1 values (40, "BO", "He gorged himself habitually at table- which made him bilious- and gave him a dim and bleared eye  and flabby cheeks. ");
insert into test1 values (41, "BP", "He ought now to have been at school- but his mama had taken him home for a month or two- “on account of his delicate health.”");
insert into test1 values (42, "BQ", " Mr. Miles- the master- affirmed that he would do very well if he had fewer cakes and sweetmeats sent him from home-");
insert into test1 values (43, "BR", " but the mother’s heart turned from an opinion so harsh- and inclined rather to ");
insert into test1 values (44, "BS", "John had not much affection for his mother and sisters- and an antipathy to me. He bullied and punished me. ");
insert into test1 values (45, "BT", " He bullied and punished me- not two or three times in the week- nor once or twice in the day- but continually: every nerve I had feared him-");
insert into test1 values (46, "BU", " and every morsel of flesh in my bones shrank when he came near. ");
insert into test1 values (47, "BV", "There were moments when I was bewildered by the terror he inspired- because I had no appeal whatever against either his menaces or his inflictions. ");
insert into test1 values (48, "BW", "the servants did not like to offend their young master by taking my part against him- and Mrs. ");
insert into test1 values (49, "BX", "Reed was blind and deaf on the subject: she never saw him strike or heard him abuse me. ");
insert into test1 values (50, "BY", "Habitually obedient to John- I came up to his chair: ");
insert into test1 values (51, "BZ", "“That is for your impudence in answering mama awhile since-” said he. ");
insert into test1 values (52, "CQ", "he spent some three minutes in thrusting out his tongue at me as far as he could without damaging the roots");
insert into test1 values (53, "CW", ": I knew he would soon strike- and while dreading the blow-");
insert into test1 values (54, "CE", " I mused on the disgusting and ugly appearance of him who would presently deal it.");
insert into test1 values (55, "CR", " I wonder if he read that notion in my face- for- all at once- without speaking- he struck suddenly and strongly.");
insert into test1 values (56, "CT", " I tottered- and on regaining my equilibrium retired back a step or two from his chair.");
insert into test1 values (57, "CY", "the more refined idea that John’s sallowness was owing to over-application and- perhaps- to pining after home.");
insert into test1 values (58, "CU", "but since dinner Mrs. Reed- when there was no company- dined early the cold winter wind had brought with it clouds so sombre");
insert into test1 values (59, "CI", "- and a rain so penetrating- that further out-door exercise was now out of the question.");
insert into test1 values (60, "CO", "dreadful to me was the coming home in the raw twilight- with nipped fingers and toes. ");
insert into test1 values (61, "CP", "and a heart saddened by the chidings of Bessie- the nurse- and humbled by the consciousness of my physical inferiority to Eliza- John- and Georgiana Reed.");
insert into test1 values (62, "CA", ": she lay reclined on a sofa by the fireside- and with her darlings about her");
insert into test1 values (63, "CS", " (for the time neither quarrelling nor crying) looked perfectly happy.");
insert into test1 values (64, "CD", " Me- she had dispensed from joining the group- saying. ");
insert into test1 values (65, "CF", "“She regretted to be under the necessity of keeping me at a distance. ");
insert into test1 values (66, "CG", "but that until she heard from Bessie- and could discover by her own observation. ");
insert into test1 values (67, "CH", "that I was endeavouring in good earnest to acquire a more sociable and childlike disposition. ");
insert into test1 values (68, "CJ", "a more attractive and sprightly manner— something lighter- franker- more natural. ");
insert into test1 values (69, "CK", "as it were—she really must exclude me from privileges intended only for contented- happy- little children.”");
insert into test1 values (70, "CL", " there is something truly forbidding in a child taking up her elders in that manner. ");
insert into test1 values (71, "CZ", "Be seated somewhere- and until you can speak pleasantly- remain silent.”");
insert into test1 values (72, "CX", "taking care that it should be one stored with pictures. I mounted into the window-seat: ");
insert into test1 values (73, "CC", "gathering up my feet- I sat cross-legged- like a Turk- and- having drawn the red moreen curtain nearly close- I was shrined in double retirement.");
insert into test1 values (74, "CV", " to the left were the clear panes of glass- protecting- but not separating me from the drear November day. ");
insert into test1 values (75, "CB", " I studied the aspect of that winter afternoon.");
insert into test1 values (76, "CN", " Afar- it offered a pale blank of mist and cloud");
insert into test1 values (77, "CM", "- near a scene of wet lawn and storm-beat shrub- with ceaseless rain sweeping away wildly before a long and lamentable blast.");
insert into test1 values (78, "DQ", "They were those which treat of the haunts of sea-fowl. ");
insert into test1 values (79, "DW", "of “the solitary rocks and promontories” by them only inhabited. ");
insert into test1 values (80, "DE", "of the coast of Norway- studded with isles from its southern extremity- the Lindeness- or Naze- to the North Cape—");
insert into test1 values (81, "DR", "that reservoir of frost and snow- where firm fields of ice- the accumulation of centuries of winters. ");
insert into test1 values (82, "DT", "glazed in Alpine heights above heights- surround the pole. ");
insert into test1 values (83, "DY", "and concentre the multiplied rigours of extreme cold.");
insert into test1 values (84, "DU", "” Of these death-white realms I formed an idea of my own: ");
insert into test1 values (85, "DI", "shadowy- like all the half-comprehended notions that float dim through children’s brains- but strangely impressive.");
insert into test1 values (86, "DO", " The words in these introductory pages connected themselves with the succeeding vignettes. ");
insert into test1 values (87, "DP", "and gave significance to the rock standing up alone in a sea of billow and spray-");
insert into test1 values (88, "DA", " to the broken boat stranded on a desolate coast- to the cold and ghastly moon glancing through bars of cloud at a wreck just sinking.");
insert into test1 values (89, "DS", "when she chanced to be in good humour- and when-");
insert into test1 values (90, "DD", " having brought her ironing-table to the nursery hearth. ");
insert into test1 values (91, "DF", "she allowed us to sit about it- and while she got up Mrs. Reed’s lace frills- and crimped her nightcap borders-");
insert into test1 values (92, "DG", " fed our eager attention with passages of love and adventure taken from old fairy tales and other ballads. ");
insert into test1 values (93, "DH", "or (as at a later period I discovered) from the pages of Pamela- and Henry- Earl of Moreland.");
insert into test1 values (94, "DJ", "though he did both now and then in her very presence- more frequently- however- behind her back.");
insert into test1 values (95, "DK", "“and for your sneaking way of getting behind curtains- and for the look you had in your eyes two minutes since- you rat!”");
insert into test1 values (96, "DL", "The breakfast-room door opened.");
insert into test1 values (97, "DZ", "“What were you doing behind the curtain?” he asked.");
insert into test1 values (98, "DX", "“I was reading.”");
insert into test1 values (99, "DC", "“Show the book.”");
insert into test1 values (100, "DV", "I returned to the window and fetched it thence.");
